In [1]:
import os
import json
import numpy as np
from tqdm import tqdm
from PIL import Image

In [2]:
root = '/home/zhmiao/datasets/ecology/CCT_15/'
img_root = os.path.join(root, 'eccv_18_all_images_sm')

In [3]:
imgs_reg = os.listdir(os.path.join(root, 'eccv_18_all_images_sm/'))

In [4]:
imgs_reg[0]

'59fae6fe-23d2-11e8-a6a3-ec086b02610b.jpg'

In [18]:
# js_path = '/home/zhmiao/datasets/ecology/CCT-20/eccv_18_annotation_files/train_annotations.json'
js_path = '/home/zhmiao/datasets/ecology/CCT_15/eccv_18_annotation_files/cis_test_annotations.json'

with open(js_path, 'r') as js:
    js_file = json.load(js)

In [19]:
cat = []
for ann in tqdm(js_file['annotations']):
    img_id = ann['image_id']
    file_path = os.path.join(img_root, img_id + '.jpg')
    
    if not os.path.isfile(file_path):
        print(file_path)
        
    if ann['category_id'] != 30:
        cat.append(ann['category_id'])

100%|██████████| 16395/16395 [00:00<00:00, 103079.10it/s]


In [20]:
js_file['categories']

[{'id': 6, 'name': 'bobcat'},
 {'id': 1, 'name': 'opossum'},
 {'id': 30, 'name': 'empty'},
 {'id': 9, 'name': 'coyote'},
 {'id': 3, 'name': 'raccoon'},
 {'id': 11, 'name': 'bird'},
 {'id': 8, 'name': 'dog'},
 {'id': 16, 'name': 'cat'},
 {'id': 5, 'name': 'squirrel'},
 {'id': 10, 'name': 'rabbit'},
 {'id': 7, 'name': 'skunk'},
 {'id': 99, 'name': 'rodent'},
 {'id': 21, 'name': 'badger'},
 {'id': 34, 'name': 'deer'},
 {'id': 33, 'name': 'car'},
 {'id': 51, 'name': 'fox'}]

In [12]:
len(js_file['categories'])

16

In [13]:
type(js_file['annotations'])

list

In [9]:
np.unique(cat)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 16, 21, 33, 34, 99])

In [21]:
np.unique(cat)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 16, 21, 33, 34, 51, 99])

In [14]:
np.unique(cat)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 16, 21, 33, 34, 51, 99])

In [48]:
np.unique(cat)

array([ 1,  3,  5,  6,  7,  8,  9, 10, 11, 16, 21, 30, 33, 34, 51, 99])

In [47]:
len(np.unique(cat))

16

In [96]:
len(np.unique(cat))

14